# Generated by Django 5.1.4 on 2024-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_factura_numero_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='abono',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='usuario_creacion',
        ),
    ]
