# Generated by Django 5.1.4 on 2024-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_factura_abono_remove_factura_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
