# Generated by Django 5.1.4 on 2024-12-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_factura_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_abonos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
