# Generated by Django 5.1.4 on 2024-12-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_factura_total_abonos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='saldo_pendiente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total_abonos',
        ),
    ]
