# Generated by Django 5.1.4 on 2024-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_abono_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_abonos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
